export const config = {
    rewardTiers: [
        { stamps: 3, drinks: 1 },
        { stamps: 5, drinks: 2 },
        { stamps: 10, drinks: 3 }
    ],
    pointRewards: [
        { points: 10, reward: "100g Free Popcorn" },
        { points: 18, reward: "Free Lemonade" }
    ],
    offers: [
        { title: "1+1 Free Lemonade", description: "Buy one, get one free!" },
        { title: "30% OFF Salt Popcorn", description: "Save on our delicious popcorn" }
    ],
    workerPin: "1234",
    redeemCooldown: 3 * 60 * 60 * 1000,
    translations: {
        en: {
            title: "Lemonade Rewards",
            clickStamps: " Click on empty stamps to collect them!",
            rewardTiers: " Reward Tiers:",
            stamps: "stamps",
            freeDrink: "free drink",
            freeDrinks: "free drinks",
            notEnoughStamps: "Not Enough Stamps",
            workerMode: " Worker Mode",
            customerMode: " Customer Mode",
            specialOffers: "Special Offers",
            points: "Points",
            settings: "Settings",
            language: "Language",
            theme: "Theme",
            light: "Light",
            dark: "Dark",
            history: "Redemption History",
            noHistory: "No redemption history yet",
            redeemed: "Redeemed",
            at: "at",
            addPoints: "Add Points",
            pointsAdded: "Added points successfully!",
            enterPoints: "Enter points to add:",
            workerLogin: "Worker Login",
            logout: "Logout",
            pointsReward1: "Redeem 10 Points for 100g Free Popcorn",
            pointsReward2: "Redeem 18 Points for Free Lemonade",
            notEnoughPoints: "Not enough points!",
            congrats: "Congratulations!",
            redeemedReward: "You've redeemed",
            waitHours: "Please wait ${hours} hours before redeeming again.",
            enterPin: "Enter worker PIN:",
            invalidPin: "Invalid PIN!",
            workerSuccess: "Worker authenticated successfully!",
            workerOnly: "Only workers can add stamps!",
            reward1: "100g Free Popcorn",
            reward2: "Free Lemonade"
        },
        pl: {
            title: "Program Lojalnościowy",
            clickStamps: " Kliknij puste pieczątki, aby je zebrać!",
            rewardTiers: " Poziomy Nagród:",
            stamps: "pieczątek",
            freeDrink: "darmowy napój",
            freeDrinks: "darmowe napoje",
            notEnoughStamps: "Za Mało Pieczątek",
            workerMode: " Tryb Pracownika",
            customerMode: " Tryb Klienta",
            specialOffers: "Oferty Specjalne",
            points: "Punkty",
            settings: "Ustawienia",
            language: "Język",
            theme: "Motyw",
            light: "Jasny",
            dark: "Ciemny",
            history: "Historia Wymian",
            noHistory: "Brak historii wymian",
            redeemed: "Wymieniono",
            at: "o",
            addPoints: "Dodaj Punkty",
            pointsAdded: "Pomyślnie dodano punkty!",
            enterPoints: "Wprowadź punkty do dodania:",
            workerLogin: "Logowanie Pracownika",
            logout: "Wyloguj",
            pointsReward1: "Wymień 10 Punktów na 100g Darmowego Popcornu",
            pointsReward2: "Wymień 18 Punktów na Darmową Lemoniadę",
            notEnoughPoints: "Niewystarczająca ilość punktów!",
            congrats: "Gratulacje!",
            redeemedReward: "Otrzymujesz",
            waitHours: "Poczekaj ${hours} godzin przed kolejną wymianą.",
            enterPin: "Wprowadź PIN pracownika:",
            invalidPin: "Nieprawidłowy PIN!",
            workerSuccess: "Pomyślnie zalogowano jako pracownik!",
            workerOnly: "Tylko pracownicy mogą dodawać pieczątki!",
            reward1: "100g Darmowego Popcornu",
            reward2: "Darmowa Lemoniada"
        }
    }
};